name: Weekly Reminder

on:
  schedule:
    - cron: '0 8 */14 * *' # כל שבועיים ב-9:00 UTC

jobs:
  send_reminder:
    runs-on: ubuntu-latest
    steps:
      - name: שלח מייל
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com          # כתובת שרת SMTP
          server_port: 587                        # פורט
          username: ${{ dudibibla@gmail.com }}      # שם המשתמש במייל (Saved in Secrets)
          password: ${{ qwas1234 }}      # סיסמא או token במייל (Saved in Secrets)
          subject: "תזכורת טוביה"
          body: "זמן טוב לתזכר את טוביה בעדכון דוד שבועי"
          to: dudibibla@gmail.com
