name: Weekly Reminder

on:
  schedule:
    - cron: '0 8 */14 * *' # כל שבועיים ב-9:00 UTC
  workflow_dispatch: {}
jobs:
  send_reminder:
    runs-on: ubuntu-latest
    steps:
      - name: שלח מייל
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com          # כתובת שרת SMTP
          server_port: 587                        # פורט
          username: ${{ secrets.MAIL_USER }}
          password: ${{ secrets.MAIL_PASS }}
          from: ${{ secrets.MAIL_USER }} 
          subject: "תזכורת טוביה"
          body: "זמן טוב לתזכר את טוביה בעדכון דוד שבועי"
          to: dudibibla@gmail.com
